Fixing the az storage account creation command in single-cluster.md (#1341)
I was doing the single cluster walkthrough and got an error when running:

```
az storage account create \
    --name mystorageaccount \
    --resource-group my-global-rg \
    --location eastus \
    --sku Standard_LRS \
    --encryption-services blob
```
error: az storage account create: error: ambiguous option: --encryption could match --encryption-services, --encryption-key-type-for-table, --encryption-key-type-for-queue

Looks like the --encryption option has changed to --encryption-services as per: https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create